### ISSUE TITLE
Doesn't work on Blender 2.82

### ISSUE THREAD

**Issue by kozlovdennis** [igelbox/blender-ogf#1]
Doesn't work on blender 2.82. Will be extremely appreciated if you could fixed it. Thanks!

**Comment by igelbox** [comment]
Well, it seems this addon became useless since we created [blender-xray](https://github.com/PavelBlend/blender-xray) (which is much much powerful).
So, I see the only right way to work with OGF - https://github.com/PavelBlend/blender-xray/issues/181#issuecomment-369566351

Also, I'd better archive this repo and set a link from the README to Pavel's blender-xray repo.
